apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: yassine-telitel-dev
spec:
  imagePullSecrets:
   - name: ghcr-pull-secret-new
  containers:
    - name: nginx
      image: ${IMAGE}
      ports:
        - containerPort: 8080
